### ISSUE TITLE
Cloud Routing Groups

### ISSUE THREAD

**Issue by telecomsxchange** [telecomsxchange/feature_requests#1]
## Routing Groups for SIP and SMPP

Enable routing groups with policies [lcr, loadbalancing, order] for SIP and SMPP traffic. This feature allows buyers to create custom routing groups and add any purchased SMS/Voice seller to the group in seconds. Each RG will have a unique prefix that the buyer can point their SMSC or SIP servers to in order for the RG logic to be used.

**Phase 1:**

Todo:

- [x]: UI/UX [Wire Frames ](https://www.figma.com/file/yW4U31XJ6bIXQLykzPzIWV/Routing-Groups?node-id=0%3A1) 

- [x]  AAA Modifications
- [x] Deploy to staging
- [x] Qos **final stages**
- [x] Released to PROD

**Phase 2:**

**Todo:**

- [ ] API - Make it programmable 
- [ ] Custom Business Rules
